test1/force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

test1/force-app/main/default/objects/Merchandise_Arch__c/Merchandise_Arch__c.object-meta.xml
<CustomObject>
    <label>Merchandise Arch</label>
    <nameField>
        <label>Merchandise Arch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise Archs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

test1/force-app/main/default/objects/Merchandise_Arch__c/fields/Merchandise_Arch_Desc__c.field-meta.xml
<CustomField>
    <fullName>Merchandise_Arch_Desc__c</fullName>
    <label>Merchandise Arch Desc</label>
    <type>TextArea</type>
</CustomField>

test1/force-app/main/default/objects/Merchandise_Arch__c/fields/Merchandise_Arch_Price__c.field-meta.xml
<CustomField>
    <fullName>Merchandise_Arch_Price__c</fullName>
    <label>Merchandise Arch Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

test1/force-app/main/default/objects/Merchandise_Arch__c/fields/Merchandise_Arch_Stock__c.field-meta.xml
<CustomField>
    <fullName>Merchandise_Arch_Stock__c</fullName>
    <label>Merchandise Arch Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test1/force-app/main/default/classes/MerchBkp.cls
public class MerchBkp {
    public static void showMerch(map <id,Merchandise__c> mer){
        Merchandise_Arch__c m;
        list<Merchandise_Arch__c> mL=new list<Merchandise_Arch__c>();
        set<id> key=mer.keySet();
        for(id k: key)
        {
        m=new Merchandise_Arch__c();
        Merchandise__c m0=mer.get(k);
        m.name=m0.name;
        m.Merchandise_Arch_Desc__c=m0.Merchandise_Desc__c;
        m.Merchandise_Arch_Price__c=m0.Merchandise_Price__c;
        m.Merchandise_Arch_Stock__c=m0.Merchandise_Stock__c;
        mL.add(m);
        }
        insert mL;
    }

}