test1/force-app/main/default/objects/Parent__c/fields/Records__c.field-meta.xml
<CustomField>
    <fullName>Records__c</fullName>
    <label>Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

test1/force-app/main/default/classes/ParTrigg.cls
public class ParTrigg {
    public static void Result(list<child__c> nec,list <child__c> oec){
        list<id> i=new list<id>();
        list<parent__c> p=new list<parent__c>();
        id i1;
        if(nec!=null){
            for(child__c c:nec){
                i1=c.Parent__c;
                i.add(i1);
            }
        }
        if(oec!=null){
            for(child__c c:oec){
                i1=c.Parent__c;
                i.add(i1);
            }
        }
        p=[select id,name, (select id from childs__r) from parent__c where id=:i];
        if(!p.isEmpty()){
            for(parent__c pa:p){
                pa.records__c=pa.childs__r.size();
            }
        }
        update p;
    }

}